name: "CD Workflow"

on:
    workflow_run:
        workflows: ["CI Workflow"]
        types:
            - completed
    workflow_dispatch:

jobs:
    deploy:
        runs-on: "ubuntu-latest"
        environment: production
        steps:
            - name: "Setup Node.js"
              uses: actions/setup-node@v6
              with:
                node-version: '20'
            
            - name: "Check Node Version"
              run: node --version
            
            - name: "Setup Vercel CLI"
              run: npm install -g vercel

            - name: "Check Vercel Version"
              run:  vercel --version
            
            - name: "Download build files"
              uses: actions/download-artifact@v4
              with: 
                name: build
                run-id: ${{github.event.workflow_run.id}}
                github-token: ${{github.token}}

            - name: "Deploy to Vercel"
              run: vercel deploy --prod --yes 
              env:
                VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
            
            - name: "URL for the project"
              run: vercel link